In [240]:
import numpy as np

In [241]:
np.set_printoptions(precision=4, suppress=True)

In [242]:
folder_name = 'data/real_stars_3072/'
# stars from center of pictures only
fnames = [
    '20160218_201934_unmod_stars_coords',
    '20160219_021934_unmod_stars_coords',
    '20160323_031848_unmod_stars_coords',
    '20160329_043931_unmod_stars_coords',
    '20160507_000119_unmod_stars_coords'
]

# stars from whole pictures
# fnames = [
#     '20151016_221239_stars_coords',
#     '20160218_201934_stars_coords',
#     '20160219_021934_stars_coords',
#     '20160323_031848_stars_coords',
#     '20160329_043931_stars_coords',
#     '20160507_000119_stars_coords'
# ]

In [243]:
import os

In [244]:
coords_list = []
for fname in fnames:
    piece = np.loadtxt(folder_name + os.sep + fname)
    
    coords_list.append(piece)

print coords_list

[array([[ 4847.,  1953.,  6067.,  2152.],
       [ 6022.,  3168.,  7278.,  3363.],
       [ 4827.,  1191.,  6037.,  1393.],
       [ 5387.,   942.,  6593.,  1127.]]), array([[ 1933.,  3897.,  3177.,  4122.],
       [ 2777.,  3043.,  4012.,  3268.],
       [ 4252.,  3977.,  5498.,  4192.],
       [ 3963.,  4948.,  5207.,  5162.],
       [  762.,  2157.,  2017.,  2413.]]), array([[  963.,  1487.,  2197.,  1711.],
       [ 1887.,  1832.,  3107.,  2042.],
       [ 3313.,  1397.,  4518.,  1587.],
       [ 6332.,  1017.,  7552.,  1147.]]), array([[ 2408.,  4422.,  3653.,  4607.],
       [ 5197.,  5122.,  6451.,  5307.],
       [ 1692.,  2848.,  2933.,  3047.]]), array([[    6.,   412.,  1273.,   677.],
       [ 1502.,  1838.,  2747.,  2048.],
       [ 2392.,  2247.,  3632.,  2443.],
       [ 3831.,  1908.,  5062.,  2088.],
       [  332.,  1418.,  1602.,  1648.]])]


In [245]:
coords = np.vstack(coords_list)
print coords

[[ 4847.  1953.  6067.  2152.]
 [ 6022.  3168.  7278.  3363.]
 [ 4827.  1191.  6037.  1393.]
 [ 5387.   942.  6593.  1127.]
 [ 1933.  3897.  3177.  4122.]
 [ 2777.  3043.  4012.  3268.]
 [ 4252.  3977.  5498.  4192.]
 [ 3963.  4948.  5207.  5162.]
 [  762.  2157.  2017.  2413.]
 [  963.  1487.  2197.  1711.]
 [ 1887.  1832.  3107.  2042.]
 [ 3313.  1397.  4518.  1587.]
 [ 6332.  1017.  7552.  1147.]
 [ 2408.  4422.  3653.  4607.]
 [ 5197.  5122.  6451.  5307.]
 [ 1692.  2848.  2933.  3047.]
 [    6.   412.  1273.   677.]
 [ 1502.  1838.  2747.  2048.]
 [ 2392.  2247.  3632.  2443.]
 [ 3831.  1908.  5062.  2088.]
 [  332.  1418.  1602.  1648.]]


In [246]:
coords /= 5
coords = coords.round()
print coords

[[  969.   391.  1213.   430.]
 [ 1204.   634.  1456.   673.]
 [  965.   238.  1207.   279.]
 [ 1077.   188.  1319.   225.]
 [  387.   779.   635.   824.]
 [  555.   609.   802.   654.]
 [  850.   795.  1100.   838.]
 [  793.   990.  1041.  1032.]
 [  152.   431.   403.   483.]
 [  193.   297.   439.   342.]
 [  377.   366.   621.   408.]
 [  663.   279.   904.   317.]
 [ 1266.   203.  1510.   229.]
 [  482.   884.   731.   921.]
 [ 1039.  1024.  1290.  1061.]
 [  338.   570.   587.   609.]
 [    1.    82.   255.   135.]
 [  300.   368.   549.   410.]
 [  478.   449.   726.   489.]
 [  766.   382.  1012.   418.]
 [   66.   284.   320.   330.]]


In [247]:
lX = coords[:, 0] # leftX coordinates
lY = coords[:, 1] # leftY coordinates
rX = coords[:, 2] # rightX coordinates
rY = coords[:, 3] # rightY coordinates

N = coords.shape[0] # number of pairs of points
M = coords.shape[1] # lX, lY, rX, rY == 4
print N, M

21 4


In [248]:
xi = np.zeros(2*N)
z = np.zeros(6)
arr = np.zeros((2*N, 6)) # matrix A

In [249]:
for i in xrange(N): # fill the xi vector
    xi[2*i] = rX[i]
    xi[2*i + 1] = rY[i]

In [250]:
for i in xrange(N): # fill the A matrix
    arr[2*i] = [lX[i], lY[i], 0, 0, 1, 0]
    
    arr[2*i + 1] = [0, 0, lX[i], lY[i], 0, 1]

In [251]:
print 'A:\n', arr, '\n'
print 'xi:\n', xi

A:
[[  969.   391.     0.     0.     1.     0.]
 [    0.     0.   969.   391.     0.     1.]
 [ 1204.   634.     0.     0.     1.     0.]
 [    0.     0.  1204.   634.     0.     1.]
 [  965.   238.     0.     0.     1.     0.]
 [    0.     0.   965.   238.     0.     1.]
 [ 1077.   188.     0.     0.     1.     0.]
 [    0.     0.  1077.   188.     0.     1.]
 [  387.   779.     0.     0.     1.     0.]
 [    0.     0.   387.   779.     0.     1.]
 [  555.   609.     0.     0.     1.     0.]
 [    0.     0.   555.   609.     0.     1.]
 [  850.   795.     0.     0.     1.     0.]
 [    0.     0.   850.   795.     0.     1.]
 [  793.   990.     0.     0.     1.     0.]
 [    0.     0.   793.   990.     0.     1.]
 [  152.   431.     0.     0.     1.     0.]
 [    0.     0.   152.   431.     0.     1.]
 [  193.   297.     0.     0.     1.     0.]
 [    0.     0.   193.   297.     0.     1.]
 [  377.   366.     0.     0.     1.     0.]
 [    0.     0.   377.   366.     0.     1.]
 [  663

In [252]:
from numpy.linalg import norm, pinv

In [253]:
p_arr = pinv(arr)
z = np.dot(p_arr, xi)
print 'Affine coefficients: \n', z

Affine coefficients: 
[   0.9949    0.0058   -0.0115    1.0016  247.9095   47.3994]


In [254]:
sigma = 2 # 2 pix error
I = np.eye(2*N)

print 'cond(A): ', np.linalg.cond(arr)
# print norm( np.dot(I - np.dot(arr, p_arr), xi) )
proba = (2*N - 6) / norm( np.dot(I - np.dot(arr, p_arr), xi) )**2
sig_theory = (1 / proba)**0.5

print 'Probability:', proba
print 'Sigma theory:', sig_theory
print 'Sigma practice', sigma

cond(A):  2139.3693465
Probability: 0.0756151024365
Sigma theory: 3.63660161767
Sigma practice 2
