In [50]:
import numpy as np

np.set_printoptions(precision=2, suppress=True)

In [51]:
fname_coords = 'data/real_stars_3072/20160507_000119_unmod_stars_coords'
coords = np.loadtxt(fname_coords)

coords /= 5
coords = coords.round()
print coords

[[    1.    82.   255.   135.]
 [  300.   368.   549.   410.]
 [  478.   449.   726.   489.]
 [  766.   382.  1012.   418.]
 [   66.   284.   320.   330.]]


In [52]:
lX = coords[:, 0] # leftX coordinates
lY = coords[:, 1] # leftY coordinates
rX = coords[:, 2] # rightX coordinates
rY = coords[:, 3] # rightY coordinates

N = coords.shape[0] # number of pairs of points
M = coords.shape[1] # lX, lY, rX, rY == 4
print N, M

5 4


In [53]:
print 'Input coordinates from %r: \n' % fname_coords, coords, '\n'

Input coordinates from 'data/real_stars_3072/20160507_000119_unmod_stars_coords': 
[[    1.    82.   255.   135.]
 [  300.   368.   549.   410.]
 [  478.   449.   726.   489.]
 [  766.   382.  1012.   418.]
 [   66.   284.   320.   330.]] 



In [54]:
xi = np.zeros(2*N)
z = np.zeros(6)
arr = np.zeros((2*N, 6)) # matrix A

In [55]:
for i in xrange(N): # fill the xi vector
    xi[2*i] = rX[i]
    xi[2*i + 1] = rY[i]

In [56]:
for i in xrange(N): # fill the A matrix
    arr[2*i] = [lX[i], lY[i], 0, 0, 1, 0]
    
    arr[2*i + 1] = [0, 0, lX[i], lY[i], 0, 1]

In [57]:
print 'A:\n', arr, '\n'
print 'xi:\n', xi

A:
[[   1.   82.    0.    0.    1.    0.]
 [   0.    0.    1.   82.    0.    1.]
 [ 300.  368.    0.    0.    1.    0.]
 [   0.    0.  300.  368.    0.    1.]
 [ 478.  449.    0.    0.    1.    0.]
 [   0.    0.  478.  449.    0.    1.]
 [ 766.  382.    0.    0.    1.    0.]
 [   0.    0.  766.  382.    0.    1.]
 [  66.  284.    0.    0.    1.    0.]
 [   0.    0.   66.  284.    0.    1.]] 

xi:
[  255.   135.   549.   410.   726.   489.  1012.   418.   320.   330.]


In [58]:
from numpy.linalg import norm, pinv

In [59]:
sigma = 2 # 2 pix error
I = np.eye(2*N)
p_arr = pinv(arr)
# print 'cond(A): ', np.linalg.cond(arr)
# print norm( np.dot(I - np.dot(arr, p_arr), xi) )
proba = (2*N - 6) / norm( np.dot(I - np.dot(arr, p_arr), xi) )**2
sig_theory = (1 / proba)**0.5

print 'Probability:', proba
print 'Sigma theory:', sig_theory
print 'Sigma practice', sigma

Probability: 0.541174105721
Sigma theory: 1.35935063973
Sigma practice 2
